"""
============================================================
  Customer Churn Predictor — Flask App
  ----------------------------------------------------------
  Web app to predict whether a telecom customer will churn.
  Uses a pre-trained Random Forest model saved as
  churn_model.pkl (generated by churn_predictor.py).

  Endpoints:
    GET  /         → returns the input form (index.html)
    POST /predict  → accepts JSON, returns JSON prediction
============================================================
"""

# ── Imports ───────────────────────────────────────────────
from flask import Flask, render_template, request, jsonify
import joblib
import pandas as pd
from pathlib import Path

# ── Create Flask app ──────────────────────────────────────
app = Flask(__name__)

# ── Load model bundle (once at startup) ───────────────────
# churn_model.pkl contains the Random Forest model, the
# StandardScaler, the feature column list, and the
# LabelEncoders — everything needed to make a prediction.
MODEL_PATH = Path(__file__).parent / 'churn_model.pkl'

try:
    bundle   = joblib.load(MODEL_PATH)
    model    = bundle['model']
    FEATURES = bundle['features']   # Exact column order the model expects
    print(f"✓ Model loaded — {len(FEATURES)} features")
except FileNotFoundError:
    print(f"⚠ Warning: churn_model.pkl not found.")
    print(f"  Run churn_predictor.py first to generate it.")
    model    = None
    FEATURES = []


# ── Home route ────────────────────────────────────────────
@app.route('/')
def home():
    return render_template('index.html')


# ── Predict route ─────────────────────────────────────────
@app.route('/predict', methods=['POST'])
def predict():
    # Check model is loaded
    if model is None:
        return jsonify({"error": "Model not loaded. Run churn_predictor.py first."}), 503

    # Parse JSON body
    data = request.get_json(silent=True)
    if data is None:
        return jsonify({"error": "Request must be JSON"}), 400

    try:
        # Build a single-row DataFrame with the exact features and
        # order the model was trained on. The form sends human-readable
        # values (e.g. "Yes"/"No", "Month-to-month") which we encode
        # the same way LabelEncoder did during training.

        # Helper: convert Yes/No strings to 1/0
        def yn(val):
            return 1 if str(val).strip().lower() in ['yes', '1', 'true'] else 0

        row = {
            'gender':           1 if str(data.get('gender', 'Male')).strip().lower() == 'male' else 0,
            'SeniorCitizen':    int(data.get('SeniorCitizen', 0)),
            'Partner':          yn(data.get('Partner', 'No')),
            'Dependents':       yn(data.get('Dependents', 'No')),
            'tenure':           float(data.get('tenure', 0)),
            'PhoneService':     yn(data.get('PhoneService', 'Yes')),
            # MultipleLines: No=0, No phone service=1, Yes=2
            'MultipleLines':    {'No': 0, 'No phone service': 1, 'Yes': 2}.get(
                                    data.get('MultipleLines', 'No'), 0),
            # InternetService: DSL=0, Fiber optic=1, No=2
            'InternetService':  {'DSL': 0, 'Fiber optic': 1, 'No': 2}.get(
                                    data.get('InternetService', 'DSL'), 0),
            # The following services use: No=0, No internet service=1, Yes=2
            'OnlineSecurity':   {'No': 0, 'No internet service': 1, 'Yes': 2}.get(
                                    data.get('OnlineSecurity', 'No'), 0),
            'OnlineBackup':     {'No': 0, 'No internet service': 1, 'Yes': 2}.get(
                                    data.get('OnlineBackup', 'No'), 0),
            'DeviceProtection': {'No': 0, 'No internet service': 1, 'Yes': 2}.get(
                                    data.get('DeviceProtection', 'No'), 0),
            'TechSupport':      {'No': 0, 'No internet service': 1, 'Yes': 2}.get(
                                    data.get('TechSupport', 'No'), 0),
            'StreamingTV':      {'No': 0, 'No internet service': 1, 'Yes': 2}.get(
                                    data.get('StreamingTV', 'No'), 0),
            'StreamingMovies':  {'No': 0, 'No internet service': 1, 'Yes': 2}.get(
                                    data.get('StreamingMovies', 'No'), 0),
            # Contract: Month-to-month=0, One year=1, Two year=2
            'Contract':         {'Month-to-month': 0, 'One year': 1, 'Two year': 2}.get(
                                    data.get('Contract', 'Month-to-month'), 0),
            'PaperlessBilling': yn(data.get('PaperlessBilling', 'Yes')),
            # PaymentMethod: Bank transfer=0, Credit card=1, Electronic check=2, Mailed check=3
            'PaymentMethod':    {
                                    'Bank transfer (automatic)': 0,
                                    'Credit card (automatic)':   1,
                                    'Electronic check':          2,
                                    'Mailed check':              3
                                }.get(data.get('PaymentMethod', 'Electronic check'), 2),
            'MonthlyCharges':   float(data.get('MonthlyCharges', 0)),
            'TotalCharges':     float(data.get('TotalCharges', 0)),
        }

        # Build DataFrame in the exact column order the model expects
        input_df = pd.DataFrame([row])[FEATURES]

        # Make prediction
        prediction  = model.predict(input_df)[0]
        probability = model.predict_proba(input_df)[0][1]  # probability of churn

        label = 'Churn' if prediction == 1 else 'No Churn'

        return jsonify({
            'prediction':  label,
            'probability': round(float(probability) * 100, 2)
        })

    except (ValueError, TypeError) as e:
        return jsonify({"error": f"Invalid input: {e}"}), 400
    except Exception as e:
        return jsonify({"error": str(e)}), 500


# ── Start server ──────────────────────────────────────────
if __name__ == '__main__':
    print("\n" + "=" * 50)
    print("  Customer Churn Predictor")
    print("  → http://localhost:5000")
    print("=" * 50 + "\n")
    app.run(debug=True, port=5001)
